//! Parses the embedded models.dev pricing snapshot.
//!
//! The snapshot is generated by `scripts/update-cost-pricing.mjs` from
//! https://models.dev/api.json and stores per-token USD rates:
//!
//! ```json
//! {
//!   "deepseek-v4-flash": { "i": 1.4e-7, "o": 2.8e-7, "cr": 2.8e-9 },
//!   "mimo-v2.5-free":    { "i": 0.0, "o": 0.0 }
//! }
//! ```

use std::collections::HashMap;

use serde::Deserialize;

const EMBEDDED_SNAPSHOT: &str = include_str!("models-dev-pricing.json");

/// Per-model per-token USD rates from the snapshot.
#[derive(Debug, Clone, Copy, PartialEq)]
pub(crate) struct PricingEntry {
    /// Input cost per token (USD).
    pub input: f64,
    /// Output cost per token (USD).
    pub output: f64,
    /// Cache-read cost per token (USD); `None` when the snapshot omits it.
    pub cache_read: Option<f64>,
    /// Cache-write (cache creation) cost per token (USD); `None` when omitted.
    pub cache_write: Option<f64>,
}

/// The embedded pricing snapshot, keyed by raw model id.
#[derive(Debug, Clone)]
pub(crate) struct PricingSnapshot {
    entries: HashMap<String, PricingEntry>,
}

impl PricingSnapshot {
    /// Load the embedded snapshot once per process.
    pub(crate) fn load() -> Self {
        let raw: HashMap<String, RawEntry> = serde_json::from_str(EMBEDDED_SNAPSHOT)
            .expect("embedded models-dev pricing snapshot must parse");
        Self {
            entries: raw
                .into_iter()
                .map(|(model, entry)| (model, entry.into()))
                .collect(),
        }
    }

    /// Look up a model's pricing by exact id, then by normalized id
    /// (dots/@ → dashes) and suffix-insensitive prefix match, mirroring the
    /// collector's fuzzy matching so `deepseek-v4-flash-0731` finds
    /// `deepseek-v4-flash`.
    pub(crate) fn find(&self, model: &str) -> Option<PricingEntry> {
        if let Some(entry) = self.entries.get(model) {
            return Some(*entry);
        }
        let normalized = model.replace(['.', '@', '/'], "-");
        if let Some(entry) = self.entries.get(&normalized) {
            return Some(*entry);
        }
        // Prefix match: a longer model id that starts with a known base.
        self.entries
            .iter()
            .filter(|(candidate, _)| {
                candidate.len() < model.len() && model.starts_with(candidate.as_str())
            })
            .max_by_key(|(candidate, _)| candidate.len())
            .map(|(_, entry)| *entry)
    }
}

#[derive(Debug, Deserialize)]
struct RawEntry {
    i: f64,
    o: f64,
    #[serde(default)]
    cr: Option<f64>,
    #[serde(default)]
    cw: Option<f64>,
}

impl From<RawEntry> for PricingEntry {
    fn from(raw: RawEntry) -> Self {
        Self {
            input: raw.i,
            output: raw.o,
            cache_read: raw.cr,
            cache_write: raw.cw,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_embedded_snapshot() {
        let snapshot = PricingSnapshot::load();
        assert!(snapshot.entries.len() > 100, "snapshot has entries");
        assert!(snapshot.find("deepseek-v4-flash").is_some());
    }

    #[test]
    fn finds_by_exact_and_normalized_id() {
        let snapshot = PricingSnapshot::load();

        let exact = snapshot.find("deepseek-v4-flash").expect("exact");
        assert!(exact.input > 0.0);
        assert!(exact.output > 0.0);

        let normalized = snapshot.find("deepseek/v4-flash").expect("normalized");
        assert_eq!(normalized.input, exact.input);
    }

    #[test]
    fn finds_by_prefix_suffix_variant() {
        let snapshot = PricingSnapshot::load();

        // A date/version-suffixed id resolves to its base model's pricing.
        let variant = snapshot.find("deepseek-v4-flash-0731").expect("variant");
        let base = snapshot.find("deepseek-v4-flash").expect("base");
        assert_eq!(variant.input, base.input);
    }

    #[test]
    fn free_models_are_zero() {
        let snapshot = PricingSnapshot::load();

        let free = snapshot.find("deepseek-v4-flash-free").expect("free model");
        assert_eq!(free.input, 0.0);
        assert_eq!(free.output, 0.0);
    }
}
